name: 'Repro'
on:
  workflow_dispatch: { }
  push:

jobs:
  run:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
      - name: 'Set up Java'
        uses: 'actions/setup-java@v4'
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: 'Setup Gradle'
        uses: 'gradle/actions/setup-gradle@v3'
      - name: 'Repro'
        run: |
          ./gradlew :compileDevelopmentExecutableKotlinJs
          sed -i 's| / 5||g' src/jsMain/kotlin/Main.kt
          ./gradlew :compileDevelopmentExecutableKotlinJs